### ISSUE TITLE
Suggest use of CDDL

### ISSUE THREAD

**Issue by athiasjerome** [oasis-open/cti-stix2-json-schemas#22]
"CDDL focuses on styles of specification that are in use in the community employing the data model as pioneered by JSON and now refined in CBOR."
Ref. https://datatracker.ietf.org/doc/draft-greevenbosch-appsawg-cbor-cddl/

**Comment by athiasjerome** [comment]
Note: Advantage of using CBOR: CBOR Object Signing and Encryption (COSE) https://datatracker.ietf.org/wg/cose/documents/

**Comment by gtback** [comment]
Thanks for the suggestion, @athiasjerome. 

Based on a quick search, it doesn't seem like there's a ton of active libraries that support CBOR. The CDDL document looks like it's still a draft. Given that the TC made a decision early on to support JSON, it's unlikely we would switch to CBOR at this point, at least as the primary data representation. 

I'm not familiar at all with COSE, (and barely familiar with the JSON equivalent JOSE), but I don't see that as being a particular reason to use CBOR instead of JSON. 

If you (or anyone else) develops an alternate, CBOR-based binding for the spec, and develops a CDDL description of the data structures, we could consider including them in this repository, but for now, I don't think this is actionable.

**Comment by gtback** [comment]
Feel free to re-open this if I've misunderstood anything.
