### ISSUE TITLE
Is Incident Model exist in STIX 2 ?

### ISSUE THREAD

**Issue by adhamai** [oasis-open/cti-stix2-json-schemas#61]
Would you please let me know if the incident model is available in STIX2. What is the latest version of the incident model?

Thank you.

**Comment by gtback** [comment]
Hi, @adhamai. Incident is not defined in the STIX 2.0 spec, but it is in development and being considered for STIX 2.1. You can follow the discussion looking at the [archives of the mailing lists](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback). 

Since this repository simply tracks the specs that are produced by the TC, there's nothing we can do here, so I'm going to close this issue. Thanks for the question, and please feel free to follow up with any other questions you have.
